server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: animation-service
          uri: lb://ANIMATION-SERVICE
          predicates:
            - Path=/animation/**
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/file/**
        - id: project-management-service
          uri: lb://PROJECT-MANAGEMENT-SERVICE
          predicates:
            - Path=/project-management/**
        - id: ai-enhancements-service
          uri: lb://AI-ENHANCEMENTS-SERVICE
          predicates:
            - Path=/ai-enhancements/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
