# ----------------------------------------------------------------------
# Default Configurations
# ----------------------------------------------------------------------
spring:
  application:
    name: animation
  profiles:
    active: local
  jackson:
    deserialization:
      accept-empty-array-as-null-object: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/animation?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: root
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      connection-timeout: 60000
      max-lifetime: 120000
      idle-timeout: 90000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
  sql:
    init:
      mode: always
    generate-ddl: true
  freemarker:
    cache: true
    settings:
      template_update_delay: 0
springfox:
  documentation:
    auto-startup: true
server:
  address: 0.0.0.0
  port: 8041
  servlet:
    context-path: /animation
